# Generated by Django 3.2.9 on 2021-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='content')),
                ('private', models.BooleanField(default=True)),
                ('pid', models.TextField(verbose_name='public id')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
